# Organization: Technosprint info Solutions
# Owner: Logaraj S
# Created at: 2026-09-01
# Description: Governed by ManageMyOpz Python coding standards.
"""`opzhubctl module-gen` — regenerates build-time module maps (doc 01 §5,
doc 06 §4). This pass regenerates the Python map directly; Java/web/Flutter
maps are hand-maintained lists (pom.xml build-helper sources, vite alias,
Dart map) until a full multi-language codegen pass is written — printed as
a follow-up reminder rather than silently doing nothing."""
from __future__ import annotations

import glob
import os

from opzhub_scripts import config, logging as opzlog


def _present_modules() -> dict[str, dict]:
    import yaml

    present: dict[str, dict] = {}
    for prefix in ("", "../../", "../"):
        for path in glob.glob(os.path.join(prefix, "modules", "*", "module.yaml")):
            with open(path, "r", encoding="utf-8") as f:
                doc = yaml.safe_load(f) or {}
            if doc.get("id"):
                present[doc["id"]] = doc
        if present:
            break
    return present


def run(args) -> int:
    settings = config.load()
    present = _present_modules()
    enabled = [m for m in settings.enabled_modules if m in present]

    python_modules = [m for m in enabled if (present[m].get("runtimes") or {}).get("python")]
    java_modules = [m for m in enabled if (present[m].get("runtimes") or {}).get("backend")]
    frontend_modules = [m for m in enabled if (present[m].get("runtimes") or {}).get("frontend")]
    mobile_modules = [m for m in enabled if (present[m].get("runtimes") or {}).get("mobile")]

    # Python map — safe to regenerate automatically (doc 01 §5).
    target = None
    for prefix in ("", "../../", "../"):
        candidate = os.path.join(prefix, "common", "python", "opzhub_kernel", "generated", "module_map.py")
        if os.path.isdir(os.path.dirname(candidate)):
            target = candidate
            break
    if target:
        with open(target, "w", encoding="utf-8") as f:
            f.write('"""BUILD ARTIFACT — regenerated by `opzhubctl module-gen` (doc 01 §5)."""\n')
            f.write("from __future__ import annotations\n\n")
            f.write(f"MODULE_PLUGIN_IMPORTS: list[str] = {python_modules!r}\n")
        print(f"module-gen: wrote {target} ({len(python_modules)} python module(s))")

    print(f"module-gen: java modules requiring pom.xml build-helper sources: {java_modules}")
    print(f"module-gen: frontend modules requiring generated/module-map.ts: {frontend_modules}")
    print(f"module-gen: mobile modules requiring generated/module_map.dart: {mobile_modules}")
    opzlog.log("module_gen", python=python_modules, java=java_modules, frontend=frontend_modules, mobile=mobile_modules)
    return 0
